language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - yoonwon.kang@gmail.com 

before_depoly:
  - zip -r toydemo *
  - mkdir -p deploy
  - mv toydemo.zip deploy/toydemo.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: demo-springboot-deploy
    region: ap-northeast-2
    local_dir : deploy
    skip_cleanup: true
    acl: public_read
    wait-util-deployed: true
    on:
      repo: yoonwonkang/toydemo
      branch: master
